use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :seed_raid, SeedRaidWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [node: ["webpack.dev.js", cd: Path.expand("../assets", __DIR__)]]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :seed_raid, SeedRaidWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/seed_raid_web/views/.*(ex)$},
      ~r{lib/seed_raid_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

config :logger, level: :info

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :seed_raid, SeedRaid.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "seed_raid_dev",
  hostname: "localhost",
  pool_size: 10

# config :seed_raid, :guild, 358_681_085_246_308_353
#
# config :seed_raid, :channels, %{
#   400_443_211_127_980_044 => %{region: :eu, side: :horde}
# }

config :seed_raid, :guild, 248_859_295_414_878_208

config :seed_raid, :channels, %{
  248_861_585_811_046_410 => %{slug: "eu-alliance", timezone: "CET", region: :eu},
  248_861_600_998_621_184 => %{slug: "eu-horde", timezone: "CET", region: :eu},
  248_901_465_291_096_064 => %{slug: "na-alliance", timezone: "EST", region: :na},
  248_861_564_008_923_147 => %{slug: "na-horde", timezone: "EST", region: :na},
  400_443_211_127_980_044 => %{slug: "eu-alliance", timezone: "CET", region: :eu}
}

import_config "dev.secret.exs"
